routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.home');
});

  Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::group(['prefix' => 'admin'],function () {
	Auth::routes();
  Route::post('login', 'Auth\LoginController@login')->name('login');

  Route::resource('listings','ListingController')->middleware('admin');
  Route::resource('plans','PlanController')->middleware('admin');
  Route::resource('enquiries','EnquiryController')->middleware('admin');
   Route::resource('issue','IssuesController')->middleware('admin');
  Route::resource('categories','CategoryController')->middleware('admin');
  Route::get('getlocation','ListingController@getlocation')->name('getlocation')->middleware('admin');
  Route::any('/','AdminController@index')->name('admin')->middleware('admin');
  Route::any('changelistingstatus','ProductController@changelistingstatus')->name('changelistingstatus')->middleware('admin');
	Route::any('changebrandingstatus','ProductController@changebrandingstatus')->name('changebrandingstatus')->middleware('admin');
	Route::any('categorylistingstatus','CategoryController@categorylistingstatus')->name('categorylistingstatus')->middleware('admin');
	Route::resource('users','UserController')->middleware('admin');
	Route::any('registered-user','UserController@registeredUser')->name('registeredUser')->middleware('admin');

  Route::any('profile-request','UserController@profileRequest')->name('profileRequest')->middleware('admin');
  Route::any('view-profile-request/{id?}','UserController@viewProfileRequest')->name('viewProfileRequest')->middleware('admin');
  Route::any('approve-profile-request/{id?}','UserController@approveProfileRequest')->name('approveProfileRequest')->middleware('admin');
  Route::any('reject-profile-request/{id?}','UserController@rejectProfileRequest')->name('rejectProfileRequest')->middleware('admin');

  Route::any('registered-packer','UserController@registeredPacker')->name('registeredPacker')->middleware('admin');
  Route::any('changeRegisteredStatus','UserController@changeRegisteredStatus')->name('changeRegisteredStatus')->middleware('admin');
  Route::any('changeTopPacker','UserController@changeTopPacker')->name('changeTopPacker')->middleware('admin');
  Route::any('changeRegisteredpackerStatus','UserController@changeRegisteredpackerStatus')->name('changeRegisteredpackerStatus')->middleware('admin');
});

// Web Auth Routes Start
Route::post('/web-logins-submit', 'Auth\WebLoginController@webauthlogin')->name('web.logins.submit');
Route::any('web-logout-submit/', 'Auth\WebLoginController@logout')->name('web.logout');
Route::any('web-login','Auth\WebLoginController@weblogin')->name('weblogin');
Route::any('web-register','Auth\WebLoginController@webRegister')->name('webRegister');
Route::any('packer-register','Auth\WebLoginController@packerRegister')->name('packerRegister');
Route::any('verify-packer','Auth\WebLoginController@verifyPacker')->name('verifyPacker');
Route::any('verify-packer-email','Auth\WebLoginController@verifyPackerEmail')->name('verifyPackerEmail');
// Web Auth Routes END

Route::resource('home','HomeController');
// Route::any('home','HomeController@index')->name('home');
Route::any('dashboard','PackersController@dashboard')->name('dashboard');
Route::any('myPurchase','PackersController@myPurchase')->name('myPurchase');
Route::any('leadbuy','PackersController@buyLead')->name('leadbuy');
Route::any('myLeads','PackersController@myLeads')->name('myLeads');
Route::any('myProfile','PackersController@myProfile')->name('myProfile');
Route::any('editMyProfile','PackersController@editMyProfile')->name('editMyProfile');
Route::any('detail-myleads/{slug?}','PackersController@myLeadsDetail')->name('myLeadsDetail');
Route::any('wallet','PackersController@userWallet')->name('wallet');
Route::any('raiseIssue/{lead_id?}','PackersController@raiseIssue')->name('raiseIssue');
Route::any('saveProfileRequest','PackersController@saveProfileRequest')->name('saveProfileRequest');


Route::any('location','HomeController@location')->name('location');
Route::any('testmail','HomeController@testmail')->name('testmail');
Route::any('paymentProceed','PaymentController@create')->name('paymentProceed');
Route::any('payment','PaymentController@payment')->name('payment');
Route::any('generateOrder','PaymentController@generateOrderID')->name('generateOrder');


Route::any('profile','HomeController@profile')->name('profile');
//Route::any('single','HomeController@single')->name('single');
Route::any('about-us','HomeController@aboutUs')->name('aboutus');
Route::any('contact-us','HomeController@contactUs')->name('contactus');
Route::any('package','HomeController@package')->name('package');
Route::any('store','HomeController@storeSingle')->name('storesingle');
Route::any('blog','HomeController@blog')->name('blog');
Route::any('blog-details','HomeController@blogDetails')->name('blogdetails');
Route::any('terms-conditions','HomeController@termsConditions')->name('termsconditions');
Route::any('error','HomeController@error')->name('error');
Route::any('category-list','HomeController@categoryList')->name('categorylist');

Route::any('create-ad','HomeController@createAd')->name('createad');
Route::any('enquiry','HomeController@enquiry')->name('enquiry');
Route::any('verifyenquiry','HomeController@verifyenquiry')->name('verifyenquiry');
Route::any('verifyEnqiryForm','HomeController@verifyEnqiryForm')->name('verifyEnqiryForm');

Route::any('/','HomeController@index')->name('home');
Route::any('/detail/{slug?}','HomeController@single')->name('detail');
Route::any('/getLocations','HomeController@getLocations')->name('getLocations');
Route::any('/{slug?}','HomeController@category')->name('category');

resources/views/admininc/css.blade.php
<link rel="stylesheet" href="{{ asset('assets/vendors/mdi/css/materialdesignicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendors/css/vendor.bundle.base.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">

<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

<script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
<link href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet">
<script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js" integrity="sha512-efUTj3HdSPwWJ9gjfGR71X9cvsrthIA78/Fvd/IN+fttQVy7XWkOAXb295j8B3cmm/kFKVxjiNYzKw9IQJHIuQ==" crossorigin="anonymous"></script>
<!-- <script src="{{ asset('assets/vendors/js/vendor.bundle.base.js') }}"></script> -->

resources/views/admininc/footer.blade.php
<footer class="footer">
	<div class="d-sm-flex justify-content-center justify-content-sm-between">
	  <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">Classimax</a>. All rights reserved.</span>
	  <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Classimax <i class="mdi mdi-heart text-danger"></i></span>
	</div>
</footer>

resources/views/admininc/header.blade.php
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="{{route('admin')}}"><img src="{{ asset('images/logo.png') }}"  alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="{{route('admin')}}">{{ config('app.name', 'Calssimax') }}</a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <div class="nav-profile-img">
            <img src="{{ asset('assets/images/faces/face1.jpg') }}" alt="image">
            <span class="availability-status online"></span>
          </div>
          <div class="nav-profile-text">
            <p class="mb-1 text-black">Admin</p>
          </div>
        </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

resources/views/admininc/js.blade.php
<script src="{{ asset('assets/vendors/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('assets/js/off-canvas.js') }}"></script>
<script src="{{ asset('assets/js/hoverable-collapse.js') }}"></script>
<script src="{{ asset('assets/js/misc.js') }}"></script>
<script src="{{ asset('assets/js/dashboard.js') }}"></script>
<script src="{{ asset('assets/js/todolist.js') }}"></script>
<script src="{{ asset('assets/js/file-upload.js') }}"></script>

resources/views/admininc/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">



    <li class="nav-item">
      <a class="nav-link" href="{{route('admin')}}">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('users.index')}}">
        <span class="menu-title">Users</span>
        <i class="mdi mdi-contacts menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('categories.index')}}">
        <span class="menu-title">Categories</span>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('listings.index')}}">
        <span class="menu-title">Listing</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('registeredUser')}}">
        <span class="menu-title">Registerd Users</span>
        <i class="mdi mdi-contacts menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('registeredPacker')}}">
        <span class="menu-title">Registerd Packers</span>
        <i class="mdi mdi-contacts menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('enquiries.index')}}">
        <span class="menu-title">Enquiries</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('profileRequest')}}">
        <span class="menu-title">Profile Requests</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="dropdown-item" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
        <span class="menu-title">Log Out</span>
        <i class="mdi mdi-logout mr-2 text-primary"></i>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
      </a>
    </li>

    <!-- <li class="nav-item">
      <a class="nav-link" href="{{route('plans.index')}}">
        <span class="menu-title">Plans</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
    </li> -->

  </ul>
</nav>