routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.home');
});

  Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::group(['prefix' => 'admin'],function () {
	Auth::routes();
  Route::post('login', 'Auth\LoginController@login')->name('login');

  Route::resource('listings','ListingController')->middleware('admin');
  Route::resource('plans','PlanController')->middleware('admin');
  Route::resource('enquiries','EnquiryController')->middleware('admin');
   Route::resource('issue','IssuesController')->middleware('admin');
  Route::resource('categories','CategoryController')->middleware('admin');
  Route::get('getlocation','ListingController@getlocation')->name('getlocation')->middleware('admin');
  Route::any('/','AdminController@index')->name('admin')->middleware('admin');
  Route::any('changelistingstatus','ProductController@changelistingstatus')->name('changelistingstatus')->middleware('admin');
	Route::any('changebrandingstatus','ProductController@changebrandingstatus')->name('changebrandingstatus')->middleware('admin');
	Route::any('categorylistingstatus','CategoryController@categorylistingstatus')->name('categorylistingstatus')->middleware('admin');
	Route::resource('users','UserController')->middleware('admin');
	Route::any('registered-user','UserController@registeredUser')->name('registeredUser')->middleware('admin');

  Route::any('profile-request','UserController@profileRequest')->name('profileRequest')->middleware('admin');
  Route::any('view-profile-request/{id?}','UserController@viewProfileRequest')->name('viewProfileRequest')->middleware('admin');
  Route::any('approve-profile-request/{id?}','UserController@approveProfileRequest')->name('approveProfileRequest')->middleware('admin');
  Route::any('reject-profile-request/{id?}','UserController@rejectProfileRequest')->name('rejectProfileRequest')->middleware('admin');

  Route::any('registered-packer','UserController@registeredPacker')->name('registeredPacker')->middleware('admin');
  Route::any('changeRegisteredStatus','UserController@changeRegisteredStatus')->name('changeRegisteredStatus')->middleware('admin');
  Route::any('changeTopPacker','UserController@changeTopPacker')->name('changeTopPacker')->middleware('admin');
  Route::any('changeRegisteredpackerStatus','UserController@changeRegisteredpackerStatus')->name('changeRegisteredpackerStatus')->middleware('admin');
});

// Web Auth Routes Start
Route::post('/web-logins-submit', 'Auth\WebLoginController@webauthlogin')->name('web.logins.submit');
Route::any('web-logout-submit/', 'Auth\WebLoginController@logout')->name('web.logout');
Route::any('web-login','Auth\WebLoginController@weblogin')->name('weblogin');
Route::any('web-register','Auth\WebLoginController@webRegister')->name('webRegister');
Route::any('packer-register','Auth\WebLoginController@packerRegister')->name('packerRegister');
Route::any('verify-packer','Auth\WebLoginController@verifyPacker')->name('verifyPacker');
Route::any('verify-packer-email','Auth\WebLoginController@verifyPackerEmail')->name('verifyPackerEmail');
// Web Auth Routes END

Route::resource('home','HomeController');
// Route::any('home','HomeController@index')->name('home');
Route::any('dashboard','PackersController@dashboard')->name('dashboard');
Route::any('myPurchase','PackersController@myPurchase')->name('myPurchase');
Route::any('leadbuy','PackersController@buyLead')->name('leadbuy');
Route::any('myLeads','PackersController@myLeads')->name('myLeads');
Route::any('myProfile','PackersController@myProfile')->name('myProfile');
Route::any('editMyProfile','PackersController@editMyProfile')->name('editMyProfile');
Route::any('detail-myleads/{slug?}','PackersController@myLeadsDetail')->name('myLeadsDetail');
Route::any('wallet','PackersController@userWallet')->name('wallet');
Route::any('raiseIssue/{lead_id?}','PackersController@raiseIssue')->name('raiseIssue');
Route::any('saveProfileRequest','PackersController@saveProfileRequest')->name('saveProfileRequest');


Route::any('location','HomeController@location')->name('location');
Route::any('testmail','HomeController@testmail')->name('testmail');
Route::any('paymentProceed','PaymentController@create')->name('paymentProceed');
Route::any('payment','PaymentController@payment')->name('payment');
Route::any('generateOrder','PaymentController@generateOrderID')->name('generateOrder');


Route::any('profile','HomeController@profile')->name('profile');
//Route::any('single','HomeController@single')->name('single');
Route::any('about-us','HomeController@aboutUs')->name('aboutus');
Route::any('contact-us','HomeController@contactUs')->name('contactus');
Route::any('package','HomeController@package')->name('package');
Route::any('store','HomeController@storeSingle')->name('storesingle');
Route::any('blog','HomeController@blog')->name('blog');
Route::any('blog-details','HomeController@blogDetails')->name('blogdetails');
Route::any('terms-conditions','HomeController@termsConditions')->name('termsconditions');
Route::any('error','HomeController@error')->name('error');
Route::any('category-list','HomeController@categoryList')->name('categorylist');

Route::any('create-ad','HomeController@createAd')->name('createad');
Route::any('enquiry','HomeController@enquiry')->name('enquiry');
Route::any('verifyenquiry','HomeController@verifyenquiry')->name('verifyenquiry');
Route::any('verifyEnqiryForm','HomeController@verifyEnqiryForm')->name('verifyEnqiryForm');

Route::any('/','HomeController@index')->name('home');
Route::any('/detail/{slug?}','HomeController@single')->name('detail');
Route::any('/getLocations','HomeController@getLocations')->name('getLocations');
Route::any('/{slug?}','HomeController@category')->name('category');

app/Enquiry.php
<?php

namespace App;
use App\Category;
use Illuminate\Database\Eloquent\Model;

class Enquiry extends Model
{
    protected $table        = 'enquiries';
    protected $primaryKey   = 'id';
    protected $fillable     = [
       'contact_name','contact_number','contact_email','source_address','source_locality','source_pin','source_house_type','source_floor','source_lift','destination_check','destination_address','destination_location','destination_pin','destination_house_type','destination_lift','quantity','status','max_purchase_count','amount','available_count','token'
    ];
    const CREATED_AT = 'created';
	const UPDATED_AT = 'modified';




	public function callSourceLocation(){
        return $this->belongsTo('App\District','source_locality','id');
    }

    public function callDestinationLocation(){
        return $this->belongsTo('App\District','destination_location','id');
    }

    public static function getCategories($parentid=''){
        $arr=[];
        $subArr=[];
        if(empty($parentid)){
            $catListing = Category::WhereNull('parent_id')->pluck('name','id')->toArray();
        }else{
            $catListing = Category::Where('parent_id',$parentid)->pluck('name','id')->toArray();
        }
        foreach ($catListing as $key => $value) {
            $arr[$key]['parent']=$value;
            $arr[$key]['menu_id']=$key;
            $subArr = Enquiry::getCategories($key);   
            if(!empty($subArr)){
                $arr[$key]['child']=[];
                $arr[$key]['child']=$subArr;
            }
        }
        return $arr;
    }

}

app/Http/Controllers/EnquiryController.php
<?php

namespace App\Http\Controllers;
use Config;
use App\User;
use App\Enquiry;
use App\Category;
use Illuminate\Http\Request;

class EnquiryController extends Controller
{
    public function __construct(){
        $this->middleware('auth:admin');
        $this->user                    = new User;
        $this->enquiry                 = new Enquiry;
        $this->category                = new Category();
        $this->status                  = Config::get('common.enquiry_status');
        $this->statusColor             = Config::get('common.enquiry_status_color');
    }

    public function index(){
        $status         = $this->status;
        $statusColor    = $this->statusColor;
        $enquiries      = $this->enquiry->latest()->paginate(15);
        return view('enquiries.index',compact('enquiries','status','statusColor'))->with('i', (request()->input('page', 1) - 1) * 15);
    }

    public function create()
    {
        
    }

    public function store(Request $request)
    {
        
    }

    public function show(Enquiry $enquiry){
        // $categorylist    = $this->enquiry->getCategories();
        $quantityArr        = [];
        if(!empty($enquiry->quantity)){
            $quantityArr    = json_decode($enquiry->quantity,true);
        }
        $categoriesArr  = $this->category->where(['status'=>1])->pluck('name','id')->toArray();
        $status         = $this->status;
        $statusColor    = $this->statusColor;
        return view('enquiries.show',compact('enquiry','status','statusColor','quantityArr','categoriesArr'));
    }

    public function edit(Enquiry $enquiry){
        $quantityArr        = [];
        if(!empty($enquiry->quantity)){
            $quantityArr    = json_decode($enquiry->quantity,true);
        }
        $categoriesArr  = $this->category->where(['status'=>1])->pluck('name','id')->toArray();
        $status         = $this->status;
        return view('enquiries.edit',compact('enquiry','status','quantityArr','categoriesArr'));
    }

    public function update(Request $request, Enquiry $enquiry)
    {
        $senMailToPacker = "No";
        $location = $enquiry['source_locality']??"";
        $this->listingValidate($request,$enquiry->id);
        $data               = $request->all();
        if($data['status'] == 1 && ($data['status'] != $enquiry['status'])){
            $senMailToPacker = "Yes";
        }
        $enquiry->update($data);
        if($senMailToPacker == "Yes"){
            $getUsers = $this->user->where(['location'=>$location,'type'=>2,'is_admin'=>0,'status'=>1])->get();
            if(!empty($getUsers)){
                foreach ($getUsers as $key => $user) {
                    $data                       = [];
                    $data                       = $user;
                    $template                   = "mail.enquiryDetailsToPackers";
                    $data['subject']            = " Enquiry request near your location ";
                    $data['to']                 = $data['email'];
                    USER::sendMail($data,$template);
                    unset($data);
                }
            }
        }
        return redirect()->route('enquiries.index')->with('success','Enquiry updated successfully');
    }

    public function destroy($id)
    {
        
    }

    private function listingValidate($request,$id=null){
        $validate['max_purchase_count']               = 'required';
        $validate['status']                           = 'required';
        $messages = [
           'max_purchase_count.required'              => __('Please Enter Max Purchase Count'),
           'status.required'                          => __('Please Select Status'),
        ];
        $request->validate($validate,$messages);  
    }
}

resources/views/enquiries/edit.blade.php
@extends('layouts.admin')
@section('content')



    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> Enquiry </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Enquiry</li>
              <li class="breadcrumb-item active" aria-current="page">Edit Enquiry</li>
            </ol>
          </nav>
        </div>

        @if ($errors->any())
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    
                    <form action="{{ route('enquiries.update',$enquiry->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                      <div class="form-group">
                        <h3>Details</h3>
                        <table class="table table-hover">
                            <tr>
                              <th>Contact Name</th>
                              <td>{{ $enquiry->contact_name??"-" }}</td>

                              <th>Contact Email</th>
                              <td>{{ $enquiry->contact_email??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Contact Number</th>
                              <td>{{ $enquiry->contact_number??"-" }}</td>

                              <th>Source Address</th>
                              <td>{{ $enquiry->source_address??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Source Location</th>
                              <td>{{ $enquiry->callSourceLocation['name']??"-" }}</td>

                              <th>Source PIN</th>
                              <td>{{ $enquiry->source_pin??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Source House Type</th>
                              <td>{{ $enquiry->source_house_type??"-" }}</td>

                              <th>Source Floor</th>
                              <td>{{ $enquiry->source_floor??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Source Lift</th>
                              <td>{{ $enquiry->source_lift??"-" }}</td>

                              <th>Designation Address</th>
                              <td>{{ $enquiry->destination_address??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Designation Location</th>
                              <td>{{ $enquiry->callDestinationLocation['name']??"-" }}</td>

                              <th>Designation PIN</th>
                              <td>{{ $enquiry->destination_pin??"-" }}</td>
                            </tr>
                            <tr>
                              <th>Designation House Type</th>
                              <td>{{ $enquiry->destination_house_type??"-" }}</td>

                              <th>Designation Lift</th>
                              <td>{{ $enquiry->destination_lift??"-" }}</td>
                            </tr>
                        </table>
                      </div>

                      <!-- enquiry listing categories START -->
                      @if(!empty($quantityArr))
                      <div class="form-group">
                        <h3>Cateories</h3>
                        <table class="table table-hover">
                            <tr>
                              <th>Category</th>
                              <th>Quantity</th>
                            </tr>
                            @foreach($quantityArr as $cat => $catVal)
                              <tr>
                                <td>{{$categoriesArr[$cat]}}</td>
                                <td>{{ $catVal??"-" }}</td>
                              </tr>
                              
                            @endforeach
                        </table>
                      </div>
                      <br>
                      <br>
                      @endif
                      <!-- enquiry listing categories END -->

                      <div class="form-group">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="exampleInputName1"><span style="color: red;">*</span> Max Purchase Count </label>
                              <input type="number" class="form-control" id="exampleInputName1" value="{{$enquiry->max_purchase_count??''}}" required="required" placeholder="Enter Max Purchase Count" name="max_purchase_count">
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                            <label for="exampleSelectstatus"><span style="color: red;">*</span> Status</label>
                            <select class="form-control" id="exampleSelectstatus" required="required" name="status">
                              @foreach($status as $key => $val)
                                <option value="{{$key}}" <?= ($enquiry->status == $key)?"Selected":""?>>{{$val}}</option>
                              @endforeach
                            </select>
                          </div>
                          </div>

                        </div>
                        
                      </div>

                      
                      
                      <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                      <a href="{{route('categories.index')}}" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
          </div>

        </div>
    </div>
    
@endsection

resources/views/enquiries/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title">Enquiry Form List</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Enquiry Form List</li>
            </ol>
            
          </nav>
        </div>

        @if ($message = Session::get('success'))
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <p class="card-description"></p>
                
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Contact Name</th>
                      <th>Contact Email</th>
                      <th>Contact Number</th>
                      <th>Source</th>
                      <th>Designation</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($enquiries as $enquery)
                    <tr>
                      <td>{{ ++$i }}</td>
                      <td>{{ $enquery->contact_name }}</td>
                      <td>{{ $enquery->contact_email }}</td>
                      <td>{{ $enquery->contact_number }}</td>
                      <td>{{ $enquery->callSourceLocation['name'] }} </td>
                      <td>{{ $enquery->callDestinationLocation['name'] }}</td>
                      <td>
                        <label class="badge badge-{{$statusColor[$enquery->status]}}">{{$status[$enquery->status]}}</label>
                      </td>
                      <td>
                        <form action="{{ route('enquiries.destroy',$enquery->id) }}" method="POST">
                            <a class="btn btn-primary btn-xs" href="{{ route('enquiries.edit',$enquery->id) }}">Edit</a>
                            <a class="btn btn-info btn-xs" href="{{ route('enquiries.show',$enquery->id) }}">View</a>
                            @csrf
                            @method('DELETE')
                            <!-- <button type="submit" class="btn btn-danger btn-xs">Delete</button> -->
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                {!! $enquiries->links() !!}
              </div>
            </div>
          </div>
        </div>
    </div>      
@endsection

resources/views/enquiries/show.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> View Enquiry </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Enquiry</li>
              <li class="breadcrumb-item active" aria-current="page">View Enquiry</li>
            </ol>
          </nav>
        </div>

        <div class="row">
          <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                  <!-- enquiry listing categories START -->
                  @if(!empty($quantityArr))
                  <div class="form-group">
                    <h3>Cateories</h3>
                    <table class="table table-hover">
                        <tr>
                          <th>Category</th>
                          <th>Quantity</th>
                        </tr>
                        @foreach($quantityArr as $cat => $catVal)
                          <tr>
                            <td>{{$categoriesArr[$cat]}}</td>
                            <td>{{ $catVal??"-" }}</td>
                          </tr>
                          
                        @endforeach
                    </table>
                  </div>
                  <br>
                  <br>
                  @endif
                  <!-- enquiry listing categories END -->

                  <div class="form-group">
                    <h3>Details</h3>
                    <table class="table table-hover">
                        <tr>
                          <th>Contact Name</th>
                          <td>{{ $enquiry->contact_name??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Contact Email</th>
                          <td>{{ $enquiry->contact_email??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Contact Number</th>
                          <td>{{ $enquiry->contact_number??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source Address</th>
                          <td>{{ $enquiry->source_address??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source Location</th>
                          <td>{{ $enquiry->callSourceLocation['name']??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source PIN</th>
                          <td>{{ $enquiry->source_pin??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source House Type</th>
                          <td>{{ $enquiry->source_house_type??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source Floor</th>
                          <td>{{ $enquiry->source_floor??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Source Lift</th>
                          <td>{{ $enquiry->source_lift??"-" }}</td>
                        </tr>

                        <tr>
                          <th>Designation Address</th>
                          <td>{{ $enquiry->destination_address??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Designation Location</th>
                          <td>{{ $enquiry->callDestinationLocation['name']??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Designation PIN</th>
                          <td>{{ $enquiry->destination_pin??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Designation House Type</th>
                          <td>{{ $enquiry->destination_house_type??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Designation Lift</th>
                          <td>{{ $enquiry->destination_lift??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Max Purchase Count</th>
                          <td>{{ $enquiry->max_purchase_count??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Amount</th>
                          <td>{{ $enquiry->amount??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Available Count</th>
                          <td>{{ $enquiry->available_count??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Status</th>
                          <td>
                            <label class="badge badge-{{$statusColor[$enquiry->status]}}">{{$status[$enquiry->status]}}</label>
                          </td>
                        </tr>
                        <tr>
                          <th colspan="2"><a href="{{route('enquiries.index')}}" class="btn btn-primary">Enquiry Listing</a></th>
                        </tr>
                    </table>
                  </div>

                </div>
            </div>
          </div>

        </div>
    </div>

@endsection