routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.home');
});

  Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::group(['prefix' => 'admin'],function () {
	Auth::routes();
  Route::post('login', 'Auth\LoginController@login')->name('login');

  Route::resource('listings','ListingController')->middleware('admin');
  Route::resource('plans','PlanController')->middleware('admin');
  Route::resource('enquiries','EnquiryController')->middleware('admin');
   Route::resource('issue','IssuesController')->middleware('admin');
  Route::resource('categories','CategoryController')->middleware('admin');
  Route::get('getlocation','ListingController@getlocation')->name('getlocation')->middleware('admin');
  Route::any('/','AdminController@index')->name('admin')->middleware('admin');
  Route::any('changelistingstatus','ProductController@changelistingstatus')->name('changelistingstatus')->middleware('admin');
	Route::any('changebrandingstatus','ProductController@changebrandingstatus')->name('changebrandingstatus')->middleware('admin');
	Route::any('categorylistingstatus','CategoryController@categorylistingstatus')->name('categorylistingstatus')->middleware('admin');
	Route::resource('users','UserController')->middleware('admin');
	Route::any('registered-user','UserController@registeredUser')->name('registeredUser')->middleware('admin');

  Route::any('profile-request','UserController@profileRequest')->name('profileRequest')->middleware('admin');
  Route::any('view-profile-request/{id?}','UserController@viewProfileRequest')->name('viewProfileRequest')->middleware('admin');
  Route::any('approve-profile-request/{id?}','UserController@approveProfileRequest')->name('approveProfileRequest')->middleware('admin');
  Route::any('reject-profile-request/{id?}','UserController@rejectProfileRequest')->name('rejectProfileRequest')->middleware('admin');

  Route::any('registered-packer','UserController@registeredPacker')->name('registeredPacker')->middleware('admin');
  Route::any('changeRegisteredStatus','UserController@changeRegisteredStatus')->name('changeRegisteredStatus')->middleware('admin');
  Route::any('changeTopPacker','UserController@changeTopPacker')->name('changeTopPacker')->middleware('admin');
  Route::any('changeRegisteredpackerStatus','UserController@changeRegisteredpackerStatus')->name('changeRegisteredpackerStatus')->middleware('admin');
});

// Web Auth Routes Start
Route::post('/web-logins-submit', 'Auth\WebLoginController@webauthlogin')->name('web.logins.submit');
Route::any('web-logout-submit/', 'Auth\WebLoginController@logout')->name('web.logout');
Route::any('web-login','Auth\WebLoginController@weblogin')->name('weblogin');
Route::any('web-register','Auth\WebLoginController@webRegister')->name('webRegister');
Route::any('packer-register','Auth\WebLoginController@packerRegister')->name('packerRegister');
Route::any('verify-packer','Auth\WebLoginController@verifyPacker')->name('verifyPacker');
Route::any('verify-packer-email','Auth\WebLoginController@verifyPackerEmail')->name('verifyPackerEmail');
// Web Auth Routes END

Route::resource('home','HomeController');
// Route::any('home','HomeController@index')->name('home');
Route::any('dashboard','PackersController@dashboard')->name('dashboard');
Route::any('myPurchase','PackersController@myPurchase')->name('myPurchase');
Route::any('leadbuy','PackersController@buyLead')->name('leadbuy');
Route::any('myLeads','PackersController@myLeads')->name('myLeads');
Route::any('myProfile','PackersController@myProfile')->name('myProfile');
Route::any('editMyProfile','PackersController@editMyProfile')->name('editMyProfile');
Route::any('detail-myleads/{slug?}','PackersController@myLeadsDetail')->name('myLeadsDetail');
Route::any('wallet','PackersController@userWallet')->name('wallet');
Route::any('raiseIssue/{lead_id?}','PackersController@raiseIssue')->name('raiseIssue');
Route::any('saveProfileRequest','PackersController@saveProfileRequest')->name('saveProfileRequest');


Route::any('location','HomeController@location')->name('location');
Route::any('testmail','HomeController@testmail')->name('testmail');
Route::any('paymentProceed','PaymentController@create')->name('paymentProceed');
Route::any('payment','PaymentController@payment')->name('payment');
Route::any('generateOrder','PaymentController@generateOrderID')->name('generateOrder');


Route::any('profile','HomeController@profile')->name('profile');
//Route::any('single','HomeController@single')->name('single');
Route::any('about-us','HomeController@aboutUs')->name('aboutus');
Route::any('contact-us','HomeController@contactUs')->name('contactus');
Route::any('package','HomeController@package')->name('package');
Route::any('store','HomeController@storeSingle')->name('storesingle');
Route::any('blog','HomeController@blog')->name('blog');
Route::any('blog-details','HomeController@blogDetails')->name('blogdetails');
Route::any('terms-conditions','HomeController@termsConditions')->name('termsconditions');
Route::any('error','HomeController@error')->name('error');
Route::any('category-list','HomeController@categoryList')->name('categorylist');

Route::any('create-ad','HomeController@createAd')->name('createad');
Route::any('enquiry','HomeController@enquiry')->name('enquiry');
Route::any('verifyenquiry','HomeController@verifyenquiry')->name('verifyenquiry');
Route::any('verifyEnqiryForm','HomeController@verifyEnqiryForm')->name('verifyEnqiryForm');

Route::any('/','HomeController@index')->name('home');
Route::any('/detail/{slug?}','HomeController@single')->name('detail');
Route::any('/getLocations','HomeController@getLocations')->name('getLocations');
Route::any('/{slug?}','HomeController@category')->name('category');

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Plan extends Model
{
    protected $table        = 'plans';
    protected $primaryKey   = 'id';
    protected $fillable     = [
        'name','price', 'discount_price','validity_type','validity','facilities','is_premium','description', 'status', 'created_at','created_by', 'updated_at', 'updated_by'
    ];

    public static function scopeSearch($query,$where=[]){
        return $query->where($where);
    }
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;
use Config;
use App\Plan;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;

class PlanController extends Controller
{
    public function __construct(){
        $this->middleware('auth:admin');
        $this->plan                 = new Plan;
        $this->validityType         = Config::get('common.validity_type');
        $this->validityTypeDropDown = Config::get('common.validity_type_dropdown');
    }

    public function index(){
        $plans   = $this->plan->latest()->paginate(10);
        return view('plans.index',compact('plans'))->with('i', (request()->input('page', 1) - 1) * 10);
    }

    public function create(){
        $validityTypeDropDown = $this->validityTypeDropDown;
        return view('plans.create',compact('validityTypeDropDown'));
    }

    public function store(Request $request){
        $data           = $request->all();
        $this->plan->create($data);
        return redirect()->route('plans.index')->with('success','Plan created successfully.');
    }

    public function show(Plan $plan){
        return view('plans.show',compact('plan'));
    }

    public function edit(Plan $plan){
        return view('plans.edit',compact('plan'));
    }

    public function update(Request $request, Plan $plan){
        $data           = $request->all();
        $plan->update($data);
        return redirect()->route('plans.index')->with('success','Plan updated successfully');
    }

    public function destroy(Plan $plan){
        $plan->delete();
        return redirect()->route('plans.index')->with('success','Plan deleted successfully');
    }
}

resources/views/plans/create.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> Add Plan </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Plan</li>
              <li class="breadcrumb-item active" aria-current="page">Add Plan</li>
            </ol>
          </nav>
        </div>

        @if ($errors->any())
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    
                    <form action="{{ route('plans.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Name </label>
                        <input type="text" class="form-control" id="exampleInputName1" required="required" placeholder="Name" name="name">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Price </label>
                        <input type="number" class="form-control" id="exampleInputName1" required="required" placeholder="Original Price" name="price">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Discount Price </label>
                        <input type="number" class="form-control" id="exampleInputName1" required="required" placeholder="Discount Price" name="discount_price">
                      </div>

                      <div class="form-group">
                        <label for="exampleSelectstatus"><span style="color: red;">*</span> Validity Type </label>
                        <select class="form-control" id="exampleSelectstatus" required="required" name="validity_type">
                          <option value="1">Select Validity Type</option>
                          @foreach($validityTypeDropDown as $vtKey => $vtDropdown)
                            <option value="{{$vtKey}}">{{$vtDropdown}}</option>
                          @endforeach
                        </select>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Number of validity </label>
                        <input type="number" class="form-control" id="exampleInputName1" required="required" placeholder="Validity" name="validity">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Mobile Number </label>
                        <input type="number" class="form-control" id="exampleInputName1" required="required" placeholder="Enter Mobile Number" name="mobile_no">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Alternate Contact Number </label>
                        <input type="number" class="form-control" id="exampleInputName1" placeholder="Enter Alternate Contact Number" name="alternate_no">
                      </div>

                      <div class="form-group">
                        <label> Upload Image</label>
                        <input type="file" name="listing_image" accept="image/*" class="file-upload-default">
                        <div class="input-group col-xs-12">
                          <input type="text" name="file" accept="image/*" class="form-control file-upload-info" disabled placeholder="Upload Image">
                          <span class="input-group-append">
                            <button name="sasa" class="file-upload-browse btn btn-gradient-primary" type="button">Upload</button>
                          </span>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="exampleTextarea1"> Description</label>
                        <textarea class="form-control" id="exampleTextarea1" rows="4" name="description"></textarea>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Slug </label>
                        <input type="text" class="form-control" id="exampleInputName1"  placeholder="Slug" name="slug">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1">Meta Title </label>
                        <input type="text" class="form-control" id="exampleInputName1" placeholder="Meta Title" name="meta_title">
                      </div>

                      <div class="form-group">
                        <label for="exampleTextarea1">Meta Description</label>
                        <textarea class="form-control" id="exampleTextarea1" rows="4" name="meta_description"></textarea>
                      </div>
                      <div class="form-group">
                        <label for="number">Position </label>
                        <input type="number" class="form-control" id="number" placeholder="Position" name="meta_title">
                      </div>
                        <div class="form-group">
                        <label for="rating"> Rating </label>
                        <select class="form-control" name="rating">

                          @for ($i=5; $i>0 ;$i--)
                          <option value="{{ $i }}">{{ $i }}</option>
                          @endfor
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="exampleSelectstatus"><span style="color: red;">*</span> Status </label>
                        <select class="form-control" id="exampleSelectstatus" required="required" name="status">
                          <option value="1">Active</option>
                          <option value="0">Inactive</option>
                        </select>
                      </div>
                      
                      <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                      <a href="{{route('listings.index')}}" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
          </div>

        </div>
    </div>
@endsection

resources/views/plans/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> Edit Listing </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Listing</li>
              <li class="breadcrumb-item active" aria-current="page">Edit Listing</li>
            </ol>
          </nav>
        </div>

        @if ($errors->any())
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    
                    <form action="{{ route('listings.update',$listing->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Name </label>
                        <input type="text" class="form-control" id="exampleInputName1" value="{{$listing->name}}" required="required" placeholder="Name" name="name">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Email </label>
                        <input type="email" class="form-control" id="exampleInputName1" value="{{$listing->email}}"  placeholder="Email" name="email">
                      </div>

                      <!-- <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Code </label>
                        <input type="text" class="form-control" id="exampleInputName1" required="required" value="{{$listing->code}}" placeholder="Code" name="code">
                      </div> -->

                      <div class="form-group">
                        <label for="exampleSelectcategory"><span style="color: red;">*</span> State</label>
                        <select class="form-control" id="exampleSelectcategory" name="state" required="required" onchange="getLocation(this.value)">
                            <option value="">Select State</option>
                            @foreach($states as $key=>$val)
                                <option value="{{$key}}" <?= ($listing->state == $key)?"Selected":""?>>{{$val}}</option>
                            @endforeach
                        </select>
                      </div>

                      <div class="form-group">
                        <label for="exampleSelectcategory"><span style="color: red;">*</span> Location</label>
                        <div class="location-input">
                          <select class="form-control" id="exampleSelectcategory" name="location" required="required">
                              <option value="">Select Location</option>
                              @foreach($districts as $key=>$val)
                                <option value="{{$key}}" <?= ($listing->location == $key)?"Selected":""?>>{{$val}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="exampleTextarea1"> Address</label>
                        <textarea class="form-control" id="exampleTextarea1" rows="4" name="address">{{$listing->address}}</textarea>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Mobile Number </label>
                        <input type="number" class="form-control" id="exampleInputName1" value="{{$listing->mobile_no}}" required="required" placeholder="Enter Mobile Number" name="mobile_no">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Alternate Contact Number </label>
                        <input type="number" class="form-control" id="exampleInputName1" value="{{$listing->alternate_no}}" placeholder="Enter Alternate Contact Number" name="alternate_no">
                      </div>

                      <div class="form-group">
                        <label> Upload Image</label>
                        <input type="file" name="listing_image" accept="image/*" class="file-upload-default">
                        <div class="input-group col-xs-12">
                          <input type="text" name="file" accept="image/*" class="form-control file-upload-info" disabled placeholder="Upload Image">
                          <span class="input-group-append">
                            <button name="sasa" class="file-upload-browse btn btn-gradient-primary" type="button">Upload</button>
                          </span>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="exampleTextarea1"> Description</label>
                        <textarea class="form-control" id="exampleTextarea1" rows="4" name="description">{{$listing->description}}</textarea>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Slug </label>
                        <input type="text" class="form-control" id="exampleInputName1" value="{{$listing->slug}}" placeholder="Slug" name="slug">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"> Meta Title </label>
                        <input type="text" class="form-control" id="exampleInputName1" value="{{$listing->meta_title}}"  placeholder="Meta Title" name="meta_title">
                      </div>

                      <div class="form-group">
                        <label for="exampleTextarea1"> Meta Description</label>
                        <textarea class="form-control" id="exampleTextarea1" rows="4" name="meta_description">{{$listing->meta_description}}</textarea>
                      </div>
                      <div class="form-group">
                        <label for="number"> Position </label>
                        <input type="number" class="form-control" id="number"  value="{{$listing->position}}" placeholder="Position" name="meta_title">
                      </div>
                        <div class="form-group">
                        <label for="rating"> Rating </label>
                        <select class="form-control" value="{{$listing->rating}}" name="rating">

                          @for ($i=5; $i>0 ;$i--)
                          @php
                          $default = "";
                            if($listing->rating == $i){
                                 $default = "selected";
                            }
                          @endphp
                        
                          <option {{ $default }}value="{{ $i }}">{{ $i }}</option>
                          @endfor
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="exampleSelectstatus"><span style="color: red;">*</span> Status </label>
                        <select class="form-control" id="exampleSelectstatus" required="required" name="status">
                          <option value="1" <?= ($listing->status == 1)?"Selected":""?>>Active</option>
                          <option value="0" <?= ($listing->status == 0)?"Selected":""?>>Inactive</option>
                        </select>
                      </div>
                      
                      <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                      <a href="{{route('listings.index')}}" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
          </div>

        </div>
    </div>
    <script>
      function getLocation(id){
          $.ajax({
              url: '{{route("getlocation")}}',
              data: { id: id},
              type: "GET",
              success: function (data) {
                  if(data != ""){
                      $('.location-input').html(data);
                  }
              }
         });
      }
    </script> 
    
@endsection

resources/views/plans/getlocation.blade.php
<select class="form-control" id="exampleSelectcategory" name="location">
  <option value="">Select Location</option>
  @foreach ($districts as $skey => $name)
      <option value="{{$skey}}">{{$name}}</option>
  @endforeach
</select>

resources/views/plans/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title">Plan</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Plan</li>
            </ol>
            
          </nav>
        </div>

        @if ($message = Session::get('success'))
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <p class="card-description"> <a class="btn btn-success btn-sm float-sm-right" href="{{ route('plans.create') }}"> Add Plan</a></p>
                
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Name</th>
                      <th>Price</th>
                      <th>Discount Price</th>
                      <th>Validity</th>
                      <th>Premium</th>
                      <th>Status</th>
                      <th width="280px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($plans as $plan)
                    <tr>
                      <td>{{ ++$i }}</td>
                      <td>{{ $plan->name }}</td>
                      <td>{{ $plan->price }}</td>
                      <td>{{ $plan->discount_price }}</td>
                      <td>{{ $plan->validity }}</td>
                      <td>{{ $plan->is_premium }}</td>
                      <td>
                        @if($plan->status == 1)
                            <label class="badge badge-success">Active</label>
                        @else
                            <label class="badge badge-danger">In-Active</label>
                        @endif
                      </td>
                      <td>
                        <form action="{{ route('plans.destroy',$plan->id) }}" method="POST">
                            <a class="btn btn-primary btn-xs" href="{{ route('plans.edit',$plan->id) }}">Edit</a>
                            <a class="btn btn-info btn-xs" href="{{ route('plans.show',$plan->id) }}">View</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                {!! $plans->links() !!}
              </div>
            </div>
          </div>
        </div>
    </div>      
@endsection

resources/views/plans/show.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> View Product </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Product</li>
              <li class="breadcrumb-item active" aria-current="page">View Product</li>
            </ol>
          </nav>
        </div>

        <div class="row">
          <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">

                  
                  <div class="form-group">
                    <table class="table table-hover">
                        <tr>
                          <th>Name</th>
                          <td>{{ $listing->name }}</td>
                        </tr>
                        <tr>
                          <th>Code</th>
                          <td>{{ $listing->code }}</td>
                        </tr>
                        <tr>
                          <th>State</th>
                          <td>{{ $states[$listing->state]??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Location</th>
                          <td>{{ $districts[$listing->location]??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Address</th>
                          <td>{{ $listing->address }}</td>
                        </tr>
                        <tr>
                          <th>Mobile Number</th>
                          <td>{{ $listing->mobile_no }}</td>
                        </tr>
                        <tr>
                          <th>Alternate Contact Number</th>
                          <td>{{ $listing->alternate_no??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Description</th>
                          <td>{{ $listing->description }}</td>
                        </tr>
                        <tr>
                          <th>Slug</th>
                          <td>{{ $listing->slug }}</td>
                        </tr>
                        <tr>
                          <th>Meta Title</th>
                          <td>{{ $listing->meta_title??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Meta Description</th>
                          <td>{{ $listing->meta_description??"-" }}</td>
                        </tr>
                        <tr>
                          <th>Status</th>
                          <td>
                             @if($listing->status == 1)
                              <label class="badge badge-success">Active</label>
                            @else
                                <label class="badge badge-danger">In-Active</label>
                            @endif
                          </td>
                        </tr>
                        <tr>
                          <th colspan="2"><a href="{{route('listings.index')}}" class="btn btn-primary">Back to Listing</a></th>
                        </tr>
                    </table>
                  </div>

                </div>
            </div>
          </div>

        </div>
    </div>

@endsection